### ISSUE TITLE
DRF 缓存配置

### ISSUE THREAD

**Issue by macroldj** [macroldj/GraduationProject#20]
1. settings 
```sh
# DRF扩展
REST_FRAMEWORK_EXTENSIONS = {
    # 缓存时间
    'DEFAULT_CACHE_RESPONSE_TIMEOUT': 60 * 60,
}
```
docker-compose redis
```yml
version: '3'
services:
  redis:
    image: redis:4.0.13 
    container_name: redis
    restart: always
    command: --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
```
